if(CMAKE_SOURCE_DIR STREQUAL CMAKE_CURRENT_SOURCE_DIR)
    set(CPACK_PACKAGE_DIRECTORY ${CMAKE_BINARY_DIR}/package)
    set(CPACK_PACKAGE_NAME srs-control)
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY
        "Control software for the SRS/VMM3a data acquisition system."
    )
    # set(CPACK_PACKAGE_VENDOR "Humantiy")
    set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
    set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
    set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})
    set(CPACK_PACKAGE_INSTALL_DIRECTORY ${CPACK_PACKAGE_NAME})
    set(CPACK_VERBATIM_VARIABLES TRUE)
    set(CPACK_RESOURCE_FILE_LICENSE ${CMAKE_SOURCE_DIR}/LICENSE.md)
    set(CPACK_RESOURCE_FILE_README ${CMAKE_SOURCE_DIR}/README.md)
    set(CPACK_PACKAGE_CONTACT "yannzhaow@gmail.com")

    if(WIN32)
        set(CPACK_GENERATOR ZIP WIX)
    elseif(APPLE)
        set(CPACK_GENERATOR TGZ productbuild)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        find_program(RPM_EXECUTABLE rpm)

        if(RPM_EXECUTABLE)
            message(STATUS "packaging in rpm system")
            set(CPACK_GENERATOR RPM)
            set(CPACK_RPM_PACKAGE_AUTOREQ ON)
        else()
            message(STATUS "packaging in deb system")
            set(CPACK_GENERATOR DEB)
            set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Yanzhao Wang")
            set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
            set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS TRUE)
        endif()
    else()
        set(CPACK_GENERATOR ZIP)
    endif()

    include(CPack)
else()
    message(
        FATAL_ERROR
        "Packaging should be done in the top level CMakeLists.txt"
    )
endif()
