name: Test coverage
on:
  schedule:
    # trigger the workflow on the every 2 am UTC
    - cron: '00 02 * * *'
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
permissions: write-all

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yanzhaow/srs_env:fedora
    strategy:
      fail-fast: false
      matrix:
        base-image: [fedora]
        build-type: [Debug]
        compiler: [gcc]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: 'true'
          ref: '${{ github.event.pull_request.head.sha }}'

      - name: pre-build
        uses: './.github/actions/pre_build_config'

      - name: build-test-submit
        run: |
          dnf install -y gcovr lcov
          cmake --workflow --preset coverage
          lcov --capture --directory build --exclude '*/test/*' --exclude '*/.conan2/*' --exclude '/usr/*' --ignore-errors unused --output-file coverage.info
          lcov --list coverage.info
        shell: bash

      - name: Upload coverage reports to Codecov
        if: github.event_name != 'pull_request'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.info
          disable_search: true
          name: codecov-test

      - name: Upload coverage reports to Codecov
        if: github.event_name == 'pull_request'
        uses: codecov/codecov-action@v5
        with:
          files: coverage.info
          disable_search: true
          name: codecov-test
