name: make-caches
on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: write-all

jobs:
  build-linux-caches:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base-image: [bullseye, jammy]
        include:
          - os: jammy
            preset: static
          - os: bullseye
            preset: static
    container:
      image: ghcr.io/yanzhaow/srs_env:${{ matrix.base-image }}
    name: ${{ matrix.base-image }}-${{ matrix.preset }}
    defaults:
      run:
        shell: bash
    env:
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: 'true'

      - uses: './.github/actions/configure_conan'

      - name: set cc and cxx
        if: matrix.os != 'fedora'
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV

      - name: build
        run: |
          conan config install utils/settings/conan/settings_user.yml
          cmake --preset ${{ matrix.preset }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: cache-delete
        run: |
          gh cache delete ${{ matrix.base-image }}-${{ matrix.preset }} || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: save cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ env.CONAN_HOME }}
          key: ${{ matrix.base-image }}-${{ matrix.preset }}
