# CD pipeline to build the project and create releases with version tags.
#
# Required secrets and variables:
#
# secrets:
# - SIGN_KEY_SECRET: A private key to sign the package, used for creating debian package.
# - SRS_GH_TOKEN : the Github token, which has the permission to make new releases.
#
# variables: none

name: release
on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
    branches:
      - master
  workflow_dispatch:

permissions: write-all

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.build.outputs.tag_name }}

    steps:
      - name: Define envs
        run: echo "CMAKE_BUILD_TYPE=Release" >> $GITHUB_ENV
      - if: github.event_name == 'push'
        run: |
          if [ "${{ github.ref_name }}" == "master" ]; then
            echo "TAG_NAME=unstable" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
      - name: Setup build type
        id: build
        run: |
          echo "tag name: ${TAG_NAME}"
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT

  build-artifacts:
    runs-on: ubuntu-latest
    outputs:
      package_filename: ${{ steps.packaging.outputs.package_filename }}
    defaults:
      run:
        shell: bash
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        os: [bullseye, jammy, fedora]
        # os: [ jammy]
        root: ['with-root', 'no-root']
        # root: ['no-root']
        include:
          - os: fedora
            preset: release
          - os: jammy
            preset: static
          - os: bullseye
            preset: static
    name: ${{ matrix.os }}-${{ matrix.root }}
    env:
      CMAKE_GENERATOR: Ninja
    container:
      image: ghcr.io/yanzhaow/srs_env:${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: recover envs
        run: |
          echo "SHA_NAME=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ needs.setup.outputs.tag_name }}" >> $GITHUB_ENV
          cd $GITHUB_WORKSPACE/..
          echo "PARENT_DIR=$PWD" >> $GITHUB_ENV
          export ROOT_VERSION=$(root-config --version | sed "s/\./\-/g")
          if [[ ${{ matrix.root }} == "with-root" ]]; then
            export DISABLE_ROOT="OFF"
            export ROOT_TAG="root-${ROOT_VERSION}"
          else 
            export DISABLE_ROOT="ON"
            export ROOT_TAG="no-root"
          fi
          echo "ROOT_TAG=${ROOT_TAG}" >> $GITHUB_ENV
          echo "DISABLE_ROOT=${DISABLE_ROOT}" >> $GITHUB_ENV

      - name: set cc and cxx
        if: matrix.os != 'fedora'
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV

      - uses: './.github/actions/configure_conan'

      - name: build
        run: |
          mkdir -p srs-install
          # conan list
          export LD_LIBRARY_PATH="/usr/local/lib64:${LD_LIBRARY_PATH}"
          if [[ "${{ matrix.os }}" == "fedora" ]]; then
            cmake --preset ${{ matrix.preset}} -DCMAKE_INSTALL_PREFIX="./srs-install" -DNO_ROOT=$DISABLE_ROOT -DUSE_SYSTEM_LIBRARIES=ON
          else
            cmake --preset ${{ matrix.preset}} -DCMAKE_INSTALL_PREFIX="./srs-install" -DNO_ROOT=$DISABLE_ROOT
          fi
          cmake --build ./build --target install -- -j2
          tar czf "srs-${{ matrix.os}}-x86-64-${{ env.SHA_NAME }}-${{ env.ROOT_TAG }}.tar.gz" "./srs-install"

      - name: cpack
        if: startsWith(github.ref, 'refs/tags/') && matrix.root == 'no-root'
        id: packaging
        run: |
          cd build
          cpack
          cd package
          export package_filename=$(ls srs-control*)
          echo "package_filename=${package_filename}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/') && matrix.root == 'no-root'
        with:
          name: package-${{ matrix.os}}-${{ matrix.root }}
          path: build/package/${{ steps.packaging.outputs.package_filename }}
          retention-days: 1

      - uses: actions/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          name: download-${{ matrix.os}}-${{ env.SHA_NAME }}-${{ matrix.root }}
          path: srs-${{ matrix.os}}-x86-64-${{ env.SHA_NAME }}-${{ env.ROOT_TAG }}.tar.gz
          retention-days: 1

  publish-rpm-package:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [setup, build-artifacts]
    container:
      image: ghcr.io/yanzhaow/srs_env:fedora
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          dnf install -y nodejs
      - uses: actions/download-artifact@v4
        id: artifacts-download
        with:
          pattern: package-fedora-*
          path: ${{ github.workspace }}/package
          merge-multiple: true

      - name: set envs
        run: |
          dnf install -y createrepo_c rpm-sign
          wget -O public-key.asc https://web-docs.gsi.de/~yanwang/repos/srs-control/public-key.asc
          echo "${{ secrets.SIGN_KEY_SECRET }}" > private-key.asc
          gpg --allow-secret-key-import --import private-key.asc
          gpg --no-default-keyring --keyring trustedkeys.gpg --import public-key.asc

          rpm --import public-key.asc
          echo "%_openpgp_sign_id $(gpg --list-secret-keys --with-colons --keyid-format LONG | awk -F: '/^sec:/ {print $5; exit}')" >> ${HOME}/.rpmmacros

          export REPO_NAME=srs-control
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "SUITE=44" >> $GITHUB_ENV
          echo "ARCHS=x86_64" >> $GITHUB_ENV
          echo "RPM_DIR=package" >> $GITHUB_ENV

      - name: create repo
        run: |
          rpm --addsign ${RPM_DIR}/*
          mkdir -p repo/fedora/${SUITE}/${ARCHS}
          cp ${RPM_DIR}/* repo/fedora/${SUITE}/${ARCHS}
          createrepo_c repo/fedora/${SUITE}/${ARCHS}

      - name: copy repo
        uses: appleboy/scp-action@v1.0.0
        with:
          source: 'repo/fedora/*'
          host: ${{ secrets.DOXY_HOST}}
          username: ${{ secrets.DOXY_USERNAME }}
          password: ${{ secrets.DOXY_HOST_PASSWORD }}
          target: '/WWW/yanwang/repos/srs-control/rpm/fedora'
          proxy_host: ${{ secrets.DOXY_PROXY_SERVER }}
          proxy_username: ${{ secrets.DOXY_USERNAME }}
          proxy_password: ${{ secrets.DOXY_HOST_PASSWORD }}
          tar_tmp_path: tmp
          overwrite: true
          strip_components: 2
          rm: true
          debug: true

  publish-deb-package:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [setup, build-artifacts]
    strategy:
      fail-fast: false
      matrix:
        os: [bullseye, jammy]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/download-artifact@v4
        id: artifacts-download
        with:
          pattern: package-${{ matrix.os }}-*
          path: ${{ github.workspace }}/package
          merge-multiple: true

      - name: install aptly
        run: |
          sudo wget -O /etc/apt/keyrings/aptly.asc https://www.aptly.info/pubkey.txt
          echo "deb [signed-by=/etc/apt/keyrings/aptly.asc] http://repo.aptly.info/release ${{ matrix.os }} main" | sudo tee -a /etc/apt/sources.list.d/aptly.list
          sudo apt update -y
          sudo apt install -y wget tree aptly

      - name: import keys
        run: |
          wget -O public-key.asc https://web-docs.gsi.de/~yanwang/repos/srs-control/public-key.asc
          echo "${{ secrets.SIGN_KEY_SECRET }}" > private-key.asc

      - name: set envs
        run: |
          gpg --allow-secret-key-import --import private-key.asc
          gpg --no-default-keyring --keyring trustedkeys.gpg --import public-key.asc
          export REPO_NAME=srs-control
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "SUITE=${{ matrix.os }}" >> $GITHUB_ENV
          echo "COMPONENT=main" >> $GITHUB_ENV
          echo "ARCHS=amd64" >> $GITHUB_ENV
          echo "DEB_DIR=package" >> $GITHUB_ENV
          echo "SNAPSHOT=${REPO_NAME}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      # - name: pull from remote
      #   id: pull_from_remote
      #   continue-on-error: true
      #   run: |
      #     aptly -architectures="$ARCHS" mirror create ${REPO_NAME}-remote https://web-docs.gsi.de/~yanwang/repos/srs-control/apt ${SUITE} ${COMPONENT}
      #     aptly mirror update ${REPO_NAME}-remote

      - name: create package
        run: |
          aptly repo create -distribution="$SUITE" -component="$COMPONENT" "$REPO_NAME"

          # if [[ "${{ steps.pull_from_remote.outcome }}" == "success" ]]; then
          #   aptly -architectures="$ARCHS" repo import "srs-control-remote" "srs-control" "Name"
          #   echo "Note: Remote apt repo alreay exists, trying to update it."
          # else
          #   echo "Note: Remote apt repo doesn't exist."
          # fi

          aptly repo add "$REPO_NAME" "$DEB_DIR"
          aptly snapshot create ${SNAPSHOT} from repo "$REPO_NAME"
          aptly publish snapshot -batch -architectures="$ARCHS" -distribution="$SUITE" -component="$COMPONENT" "$SNAPSHOT"
          mv ~/.aptly/public/ ${{ matrix.os }}/

      - name: copy repo
        uses: appleboy/scp-action@v1.0.0
        with:
          source: ${{ matrix.os }}/*
          host: ${{ secrets.DOXY_HOST}}
          username: ${{ secrets.DOXY_USERNAME }}
          password: ${{ secrets.DOXY_HOST_PASSWORD }}
          target: '/WWW/yanwang/repos/srs-control/apt'
          proxy_host: ${{ secrets.DOXY_PROXY_SERVER }}
          proxy_username: ${{ secrets.DOXY_USERNAME }}
          proxy_password: ${{ secrets.DOXY_HOST_PASSWORD }}
          overwrite: true

  publish-release:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.SRS_GH_TOKEN }}
    defaults:
      run:
        shell: bash
    permissions: write-all
    needs: [setup, build-artifacts]
    steps:
      - uses: actions/checkout@v4

      - name: envs
        run: |
          export TAG_NAME=${{ needs.setup.outputs.tag_name }}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          cd ${GITHUB_WORKSPACE}/..
          mkdir download-cache && cd download-cache
          echo "DOWNLOAD_DIR=$PWD" >> $GITHUB_ENV
          if [ $TAG_NAME == "unstable" ]; then
            echo "TITLE=\"Release of unstable master branch\"" >> $GITHUB_ENV
            echo "PRERELEASE=--prerelease" >> $GITHUB_ENV
          else
            echo "TITLE=\"Release of version $TAG_NAME\"" >> $GITHUB_ENV
            echo "PRERELEASE=" >> $GITHUB_ENV
          fi

      - uses: actions/download-artifact@v4
        id: artifacts-download
        with:
          pattern: download-*
          path: ${{ env.DOWNLOAD_DIR }}

      - name: clean old releases
        continue-on-error: true
        run: gh release delete ${{ env.TAG_NAME }} --cleanup-tag || true

      - name: create release
        run: |
          gh release create ${{ env.TAG_NAME }} ${{ env.PRERELEASE }} --generate-notes --title ${{ env.TITLE }} --target $GITHUB_SHA ${{ steps.artifacts-download.outputs.download-path}}/*/*.tar.gz
