name: sanitizer
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions: write-all

jobs:
  sanitizer-test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yanzhaow/srs_env:fedora
    strategy:
      fail-fast: false
      matrix:
        sanitizer-type:
          - thread
          - address
          - UB
          - leak
        include:
          - sanitizer-type: thread
            enable-asan: 'FALSE'
            enable-tsan: 'TRUE'
            check-type: 'ThreadSanitizer'
          - sanitizer-type: address
            enable-asan: 'TRUE'
            enable-tsan: 'FALSE'
            check-type: 'AddressSanitizer'
          - sanitizer-type: UB
            enable-asan: 'TRUE'
            enable-tsan: 'FALSE'
            check-type: 'UndefinedBehaviorSanitizer'
          - sanitizer-type: leak
            enable-asan: 'TRUE'
            enable-tsan: 'FALSE'
            check-type: 'LeakSanitizer'
    name: ${{ matrix.sanitizer-type }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: 'true'

      - uses: './.github/actions/configure_conan'

      - name: set env variables for cdash
        run: |
          export PULL_NR=${{ github.event.number }}
          echo "TEST_NAME=\"${{ matrix.sanitizer-type }} sanitizer (pr.${PULL_NR})\"" >> $GITHUB_ENV

      - name: build-test-submit
        run: |
          ctest -S cmake/ci/project_sanitizer.cmake -VV\
            -DCTEST_BUILD_NAME=${{ env.TEST_NAME }}\
            -DCTEST_SITE="Github CI/CD"\
            -DCTEST_MEMORYCHECK_TYPE=${{ matrix.check-type }}\
            -DENABLE_ASAN=${{ matrix.enable-asan }}\
            -DENABLE_TSAN=${{ matrix.enable-tsan }}\
            -DADDITIONAL_CONFIGURE_OPTIONS="-DUSE_SYSTEM_LIBRARIES=ON"\
            --output-on-failure
