name: static_analysis
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions: write-all

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        base-image: [fedora]
    container:
      image: ghcr.io/yanzhaow/srs_env:${{ matrix.base-image }}
    name: clang-tidy checks
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: 'true'
      - uses: './.github/actions/configure_conan'

      - name: build-test-submit
        run: |
          cmake --preset clang -DENABLE_CLANG_TIDY=ON -GNinja -DUSE_SYSTEM_LIBRARIES=ON
          cmake --build build -- -j4 -k0

  clang-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'backend'
          - 'test/backend'
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.16.0
        with:
          clang-format-version: '21'
          check-path: ${{ matrix.path }}
          exclude-regex: '(.*LinkDef.hpp$|./*\.proto$)'
